image: tmaier/docker-compose:latest

variables:
  DOCKER_TLS_CERTDIR: ""
  COMPOSE_FILE: compose.yaml

services:
  - docker:dind

before_script:
  - docker-compose --version

stages:
  - docker-ci

fixer-tests:
  stage: docker-ci
  script:
    - docker-compose -f ${COMPOSE_FILE} build --pull &> /dev/nul
    - docker-compose -f ${COMPOSE_FILE} up -d
    - docker-compose -f ${COMPOSE_FILE} ps
    - sleep 30
    - docker-compose -f ${COMPOSE_FILE} ps
    - docker-compose -f ${COMPOSE_FILE} exec -T core composer validate --no-check-publish
    - docker-compose -f ${COMPOSE_FILE} exec -T core composer install --prefer-dist &> /dev/nul
    - docker-compose -f ${COMPOSE_FILE} exec -T core composer fix-diff
    - docker-compose -f ${COMPOSE_FILE} exec -T core composer stan
    - docker-compose -f ${COMPOSE_FILE} exec -T core composer test
    - >
      docker-compose -f ${COMPOSE_FILE} exec -T core
      bin/console doctrine:query:sql 'select id, line from app.poem'
