services:

  core:
    build:
      context: docker
      dockerfile: Dockerfile
    container_name: core
    restart: always
    volumes:
      - ./docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./core:/var/www/html
    depends_on:
      - nginx
      - db
    env_file:
      - ./core/.env
    networks:
      - start

  db:
    image: postgres:15
    container_name: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    env_file:
      - ./core/.env
    ports:
      - "7432:5432"
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    depends_on:
      - nginx
    networks:
      - start

  nginx:
    image: nginx
    container_name: nginx
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./core:/var/www/html
    ports:
      - "7080:80"
    restart: always
    networks:
      - start

networks:
  start:
    driver: bridge

volumes:
  db-data:
